export const WEBSOCKET_PORT = 6666

//const GAME_TICK_RATE = 30

export const [MAP_WIDTH, MAP_HEIGHT] = [10000, 10000]

export const PLAYER_INIT_RADIUS = 10

export const INIT_NUM_NPC_BUBBLES = Math.floor(
    (MAP_WIDTH * MAP_HEIGHT) / (PLAYER_INIT_RADIUS ** PLAYER_INIT_RADIUS) / 4
)
